# Cheatsheets

Quick reference resources for tools related to research software development and bioinformatics.

::: {.callout-tip title="Template for contributing" collapse="true"}

## Name of the tool

**Category:** [Type of tool](https://nbisweden.github.io/Training-Tech-shorts/<MAIN_CATEGORY>)

**About:** One line introduction about the tool

**Links:** [Official cheatsheet](url) | [Official documentation](url) | [Other relevant link](url)

**RSE tools sessions:** [Session title](https://nbisweden.github.io/Training-Tech-shorts/posts/<FILENAME>)

:::

## Apptainer

**Category:** [Container platform](https://nbisweden.github.io/Training-Tech-shorts/#category=Containers)

**About:** Open-source fork of Singularity, used to package applications with their dependencies for HPC environments

**Links:** [Official documentation](https://apptainer.org/docs/user/latest/) | [Coderefinery tutorial](https://coderefinery.github.io/hpc-containers/)

**RSE tools sessions:** [Introduction to Apptainer](https://nbisweden.github.io/Training-Tech-shorts/posts/2024-06-04-apptainer-intro/)

## Docker

**Category:** [Container platform](https://nbisweden.github.io/Training-Tech-shorts/#category=Containers)

**About:** Package applications with their dependencies

**Links:** [Official cheatsheet](https://docs.docker.com/get-started/docker_cheatsheet.pdf) | [Official documentation](https://docs.docker.com/)

## Git

**Category:** [Version control](https://nbisweden.github.io/Training-Tech-shorts/#category=Version%20control)

**About:** Make and manage git repositories for version control of code, documentation, and other projects

**Links:** [Official cheatsheet](https://git-scm.com/cheat-sheet) | [Official documentation](https://git-scm.com/book/en/v2) | [Cheatsheet from GitHub](https://education.github.com/git-cheat-sheet-education.pdf)

**RSE tools sessions:** [Introduction to Git](https://nbisweden.github.io/Training-Tech-shorts/posts/2024-03-19-git-intro/)

## Pixi

**Category:** [Package management](https://nbisweden.github.io/Training-Tech-shorts/#category=Package%20management)

**About:** Powerful and fast software environment creator, package manager, and task runner

**Links:** [Official quick start guide](https://pixi.sh/latest/getting_started/) | [Official documentation](https://pixi.sh/latest/)

**RSE tools sessions:** [Introduction to Pixi](https://nbisweden.github.io/Training-Tech-shorts/posts/2025-01-21-pixi-intro/)

## VSCode

**Category:** [Development environment](https://nbisweden.github.io/Training-Tech-shorts/#category=IDE)

**About:** Powerful and customizable code editor owned and supported by Microsoft

**Links:** [Official cheatsheet Windows](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf) | [Official cheatsheet MacOS](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf) | [Official documentation](https://code.visualstudio.com/docs)

**RSE tools sessions:** [Introduction to VSCode](https://nbisweden.github.io/Training-Tech-shorts/posts/2025-02-18-vscode-intro/)
