# Schedule

Dates for each walkthrough, listed in reverse chronological order.
Meetings are over Zoom, Thursdays at 10.00. Meeting links are
provided in NBIS Slack `#tech-group-rse-tools`.

- 2026/01/22: TBD
- 2026/01/08: _postponed_
- 2025/12/25: _Holiday_
- 2025/12/11: Mahesh - Good practices in Nextflow
- 2025/11/27: Mahesh - Nextflow Foundations
- 2025/11/13: Pavlin - Pixi on HPC
- 2025/10/23: Martin + Björn - Introduction to Docker
- 2025/10/09: Mahesh - Introduction to RSE Tools Tech Group
- **Renamed to RSE Tools Tech Group**
- **Break**
- 2025/06/10: Mahesh - Github Container Registry and Seqera Container Registry
- 2025/05/27: Everyone - Personal tips and tricks
- 2025/05/13: Mahesh - When is Nextflow suitable
- 2025/04/29: Mahesh - Review: SSH config
- 2025/04/15: Mahesh - SSH config
- 2025/04/01: Amrei - Review: Github profile README
- 2025/03/18: Amrei - Github profile README
- 2025/03/04: Cormac - Review: VSCode
- 2025/02/18: Cormac - VSCode
- 2025/02/04: Mahesh - Review: Pixi
- 2025/01/21: Mahesh - Pixi
- **Break**
- 2024/06/18: No lesson - SciLifeLab Facility Forum
- 2024/06/11: Cormac - Review: Singuarity
- 2024/06/04: Cormac - Singularity
- 2024/05/28: Mahesh - Review: Introduction to Gitpod.
- 2024/05/21: Tomas - Review: Quarto to Confluence.
- 2024/05/14: Tomas - Quarto to Confluence.
- 2024/05/07: Mahesh - Introduction to Gitpod.
- 2024/04/30: No lesson - Reduced working day.
- 2024/04/23: Per - Review: Quarto Introduction.
- 2024/04/16: Per - Quarto Introduction.
- 2024/04/09: No lesson - NBIS retreat.
- 2024/04/02: Mahesh - Review: Introduction to Git.
- 2024/03/26: Mahesh - Review: Collaboration in Github.
- 2024/03/19: Mahesh - Introduction to Git.
- 2024/03/12: Mahesh - Collaboration in Github.
