name: quarto-env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.15
  - biopython=1.83
  - matplotlib=3.4.2
  - pandas=2.0.3
  - numpy=1.24.4
  - jupyter
  - r-base
  - r-ggplot2
  - r-rmarkdown
  - r-reticulate
  - nb_conda_kernels
  - plotly
  - scipy=1.7.0
